spring:
  application:
    name: restAPI
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:tcp://localhost/~/account_test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true